import { describe, expect, it, beforeAll, afterAll, beforeEach } from "vitest";
import { app } from "../src/app.js";
import { mkdirSync, rmSync, readdirSync, writeFileSync } from "node:fs";
import { resolve, join } from "node:path";
import { tmpdir } from "node:os";
import { mkdtempSync } from "node:fs";
import sharp from "sharp";

const TOKEN = "test-token-123";

let TEST_DIR: string;
let AVATARS_DIR: string;
let ROOMS_DIR: string;

// Real decodable fixtures generated by sharp
let VALID_PNG: Buffer;
let VALID_JPEG: Buffer;
let VALID_WEBP: Buffer;

function authHeaders(): Record<string, string> {
  return { Authorization: `Bearer ${TOKEN}` };
}

function makeFormData(filename: string, data: Buffer | Uint8Array, mime: string): FormData {
  const form = new FormData();
  form.append("file", new File([data], filename, { type: mime }));
  return form;
}

function cleanDir(dir: string) {
  try {
    const files = readdirSync(dir);
    for (const f of files) {
      rmSync(resolve(dir, f), { force: true });
    }
  } catch { /* dir may not exist */ }
}

beforeAll(async () => {
  TEST_DIR = mkdtempSync(join(tmpdir(), "lamplight-assets-test-"));
  AVATARS_DIR = join(TEST_DIR, "avatars");
  ROOMS_DIR = join(TEST_DIR, "rooms");

  process.env.OWNER_TOKEN = TOKEN;
  process.env.ASSETS_DIR = TEST_DIR;

  mkdirSync(AVATARS_DIR, { recursive: true });
  mkdirSync(ROOMS_DIR, { recursive: true });

  // Generate real decodable 2×2 pixel images via sharp
  const pixel = sharp({ create: { width: 2, height: 2, channels: 3, background: { r: 128, g: 64, b: 32 } } });
  VALID_PNG = await pixel.clone().png().toBuffer();
  VALID_JPEG = await pixel.clone().jpeg().toBuffer();
  VALID_WEBP = await pixel.clone().webp().toBuffer();
});

beforeEach(() => {
  cleanDir(AVATARS_DIR);
  cleanDir(ROOMS_DIR);
});

afterAll(() => {
  rmSync(TEST_DIR, { recursive: true, force: true });
  delete process.env.ASSETS_DIR;
});

describe("Assets API", () => {
  describe("GET /assets/:type (manifest)", () => {
    it("returns empty manifest for empty directory", async () => {
      const res = await app.request("/assets/avatars", { headers: authHeaders() });
      expect(res.status).toBe(200);
      const body = await res.json();
      expect(body.ok).toBe(true);
      expect(body.data).toEqual({});
    });

    it("returns manifest with uploaded files", async () => {
      await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.png", VALID_PNG, "image/png"),
      });

      const res = await app.request("/assets/avatars", { headers: authHeaders() });
      const body = await res.json();
      expect(body.ok).toBe(true);
      expect(body.data.xiaoke).toBe("/assets/avatars/xiaoke.png");
    });

    it("rejects invalid asset type", async () => {
      const res = await app.request("/assets/invalid", { headers: authHeaders() });
      expect(res.status).toBe(400);
    });
  });

  describe("POST /assets/:type/:id (upload)", () => {
    it("accepts valid PNG upload", async () => {
      const res = await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.png", VALID_PNG, "image/png"),
      });
      expect(res.status).toBe(201);
      const body = await res.json();
      expect(body.ok).toBe(true);
      expect(body.data.url).toBe("/assets/avatars/xiaoke.png");

      const files = readdirSync(AVATARS_DIR);
      expect(files).toContain("xiaoke.png");
    });

    it("accepts valid JPEG upload", async () => {
      const res = await app.request("/assets/avatars/lucien", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.jpg", VALID_JPEG, "image/jpeg"),
      });
      expect(res.status).toBe(201);
      const body = await res.json();
      expect(body.data.url).toBe("/assets/avatars/lucien.jpg");
    });

    it("accepts valid WebP upload", async () => {
      const res = await app.request("/assets/rooms/room-living-room", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("room.webp", VALID_WEBP, "image/webp"),
      });
      expect(res.status).toBe(201);
      const body = await res.json();
      expect(body.data.url).toBe("/assets/rooms/room-living-room.webp");
    });

    it("rejects SVG (active content security risk)", async () => {
      const svg = Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>');
      const res = await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.svg", svg, "image/svg+xml"),
      });
      expect(res.status).toBe(400);

      const files = readdirSync(AVATARS_DIR);
      expect(files).not.toContain("xiaoke.svg");
    });

    it("rejects truncated PNG (only signature, no pixel data)", async () => {
      const truncated = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
      const res = await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.png", truncated, "image/png"),
      });
      expect(res.status).toBe(400);
    });

    it("rejects PNG with valid header but no pixel data (header-only)", async () => {
      // PNG sig + IHDR + IEND but no IDAT — sharp cannot decode pixels
      const sig = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
      const ihdr = Buffer.from([
        0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52,
        0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
        0x08, 0x02, 0x00, 0x00, 0x00, 0x90, 0x77, 0x53, 0xDE,
      ]);
      const iend = Buffer.from([0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82]);
      const headerOnly = Buffer.concat([sig, ihdr, iend]);
      const res = await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.png", headerOnly, "image/png"),
      });
      expect(res.status).toBe(400);
    });

    it("rejects JPEG with valid markers but corrupted scan data", async () => {
      // Take a real JPEG and corrupt the scan data section
      const corrupted = Buffer.from(VALID_JPEG);
      // Zero out everything after the first 20 bytes (destroys scan data)
      corrupted.fill(0, 20);
      const res = await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.jpg", corrupted, "image/jpeg"),
      });
      expect(res.status).toBe(400);
    });

    it("rejects WebP with valid RIFF header but corrupted frame", async () => {
      const corrupted = Buffer.from(VALID_WEBP);
      corrupted.fill(0, 20);
      const res = await app.request("/assets/rooms/room-1", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("room.webp", corrupted, "image/webp"),
      });
      expect(res.status).toBe(400);
    });

    it("rejects random bytes with image MIME type", async () => {
      const garbage = Buffer.alloc(256);
      for (let i = 0; i < 256; i++) garbage[i] = i;
      const res = await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.png", garbage, "image/png"),
      });
      expect(res.status).toBe(400);
    });

    it("rejects GIF (unsupported format)", async () => {
      const gif = Buffer.from("GIF89a\x01\x00\x01\x00\x80\x00\x00\xff\xff\xff\x00\x00\x00!\xf9\x04\x00\x00\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;");
      const res = await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.gif", gif, "image/gif"),
      });
      expect(res.status).toBe(400);
    });

    it("rejects oversized avatar", async () => {
      const big = new Uint8Array(501 * 1024);
      big[0] = 0x89; big[1] = 0x50; big[2] = 0x4E; big[3] = 0x47;
      const res = await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("big.png", big, "image/png"),
      });
      expect(res.status).toBe(400);
      expect((await res.json()).error.message).toContain("too large");
    });

    it("replaces existing file on re-upload", async () => {
      await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.png", VALID_PNG, "image/png"),
      });

      await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.jpg", VALID_JPEG, "image/jpeg"),
      });

      const files = readdirSync(AVATARS_DIR);
      expect(files).toContain("xiaoke.jpg");
      expect(files).not.toContain("xiaoke.png");
    });

    it("rejects invalid asset type", async () => {
      const res = await app.request("/assets/scripts/evil", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("evil.png", VALID_PNG, "image/png"),
      });
      expect(res.status).toBe(400);
    });

    it("rejects invalid id characters", async () => {
      const res = await app.request("/assets/avatars/bad%20name", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.png", VALID_PNG, "image/png"),
      });
      expect(res.status).toBe(400);
    });
  });

  describe("GET /assets/:type/:filename (static serving)", () => {
    it("serves uploaded file with correct content type", async () => {
      await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.png", VALID_PNG, "image/png"),
      });

      const res = await app.request("/assets/avatars/xiaoke.png", { headers: authHeaders() });
      expect(res.status).toBe(200);
      expect(res.headers.get("content-type")).toBe("image/png");
      expect(res.headers.get("x-content-type-options")).toBe("nosniff");
    });

    it("serves files WITHOUT auth (public for <img> tags)", async () => {
      await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.png", VALID_PNG, "image/png"),
      });

      const res = await app.request("/assets/avatars/xiaoke.png");
      expect(res.status).toBe(200);
      expect(res.headers.get("content-type")).toBe("image/png");
    });

    it("returns 404 for non-existent file", async () => {
      const res = await app.request("/assets/avatars/nobody.png");
      expect(res.status).toBe(404);
    });

    it("blocks path traversal via encoded backslash (..%5C)", async () => {
      writeFileSync(join(TEST_DIR, "secret.txt"), "do-not-read");

      const res = await app.request("/assets/avatars/..%5Csecret.txt");
      expect(res.status).toBe(404);
    });

    it("blocks path traversal via encoded slash (..%2F)", async () => {
      writeFileSync(join(TEST_DIR, "secret.txt"), "do-not-read");

      const res = await app.request("/assets/avatars/..%2Fsecret.txt");
      expect(res.status).toBe(404);
    });

    it("blocks double-dot traversal (../)", async () => {
      writeFileSync(join(TEST_DIR, "secret.txt"), "do-not-read");

      const res = await app.request("/assets/avatars/../secret.txt");
      // Router resolves ../ before handler — lands on /assets/secret.txt (not a valid type)
      expect(res.status).not.toBe(200);
    });
  });

  describe("DELETE /assets/:type/:id", () => {
    it("deletes existing asset", async () => {
      await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        headers: authHeaders(),
        body: makeFormData("avatar.png", VALID_PNG, "image/png"),
      });

      const res = await app.request("/assets/avatars/xiaoke", {
        method: "DELETE",
        headers: authHeaders(),
      });
      expect(res.status).toBe(200);
      const body = await res.json();
      expect(body.ok).toBe(true);

      const files = readdirSync(AVATARS_DIR);
      expect(files).not.toContain("xiaoke.png");
    });

    it("returns 404 for non-existent asset", async () => {
      const res = await app.request("/assets/avatars/nobody", {
        method: "DELETE",
        headers: authHeaders(),
      });
      expect(res.status).toBe(404);
    });
  });

  describe("auth enforcement", () => {
    it("manifest requires auth", async () => {
      const res = await app.request("/assets/avatars");
      expect(res.status).toBe(401);
    });

    it("upload requires auth", async () => {
      const res = await app.request("/assets/avatars/xiaoke", {
        method: "POST",
        body: makeFormData("avatar.png", VALID_PNG, "image/png"),
      });
      expect(res.status).toBe(401);
    });

    it("delete requires auth", async () => {
      const res = await app.request("/assets/avatars/xiaoke", { method: "DELETE" });
      expect(res.status).toBe(401);
    });
  });
});
